# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: 
      - main

jobs:
  build:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging
        
    - name: Maven cache
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2${{ hashFiles('**/pom.xl') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Persist artifacts
      uses: actions/upload-articaft@v3
      with:
        name: github-actions-artifact
        path: staging
